### ISSUE TITLE
Readme clarity

### ISSUE THREAD

**Issue by MichaelVessia** [adelphimathcs/repoBuilder#3]
Users who don't have the github_api will get an error if they try to run the program.  Maybe detailing how to install this would help

**Comment by MattMatero** [comment]
Will amend the readme in the morning; Anything else you think I should mention?

**Comment by MichaelVessia** [comment]
Maybe we can raise exceptions for common errors (key.txt missing,  not on individual lines, etc) and have a little section on how to address them?  

also maybe link to ruby install info in the "how to use it" section incase they dont have ruby

**Comment by MattMatero** [comment]
Error handling will be added once features are actually working. This is still an 'alpha' stage utility so I didn't put much care into error handling(clearly seen by me not catching the error if you try to create a repo that already exists). 

A guide to install ruby maybe can be added into the readme. I need to adjust a few things in it anyway.

**Comment by MattMatero** [comment]
I updated the readme to have a link for installing ruby on windows and also how to install on debian based systems. I also bolded certain parts for readability. As well as adding a link for a guide on how to register an app for client_id and client_secret. 

Maybe explicitly stating to run the script using windows powershell instead of regular cmd prompt may be necessary? I'm unsure.
